
comment: false

coverage:
    range: 25..100
    round: down
    precision: 1
    status:
        project:
            default:
                target: 50%
                threshold: 10%
        patch:
            default:
                target: 50%
                threshold: 10%
