
comment: false

coverage:
    range: 25..100
    round: down
    precision: 1
    status:
        project:
            default:
                target: auto
                threshold: 0%
        patch:
            default:
                target: 60%
                threshold: 0%
