
comment: false

coverage:
    range: 25..100
    round: down
    precision: 1
    status:
        project:
            default:
                target: auto
                threshold: 1%
        patch:
            default:
                target: auto
                threshold: 1%
