
version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:latest

    steps:
      - checkout

      - run:
          name: Runs tests / checks
          command: echo Hello world
          
      - run:
          name: Code Coverage
          command: |
            echo "hello world" 
            echo "$magicvar"
            echo "$KEY"
            echo "$CIRCLE_USERNAME"
            echo "${CIRCLE_PR_USERNAME:-not a fork}"          
      
      
      
      

