version: 2
jobs:
  build:
    docker:
      - image: rocker/tidyverse:latest
    steps:
      - checkout  
      - run: 
        name: lots of echos
        command: |
          echo "hello world" 
          echo "$magicvar"
          echo "$KEY"
          echo "$CIRCLE_USERNAME"
          echo "${CIRCLE_PR_USERNAME:-not a fork}""
