version: 2
jobs:
  build:
    docker:
      - image: rocker/tidyverse:latest

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world. > test.txt

      - run:
          name: Print the Current Time
          command: cat test.txt
          
      - run:
          name: view directory contents
          command: ls * 
          
      - run:
          name: test R
          command: Rscript -e "print('hello, world')"
          
      - run:
          name: cause an error
          command: apodpoawd
