version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world. > test.txt

      - run:
          name: Print the Current Time
          command: cat test.txt
